name: Daily wireguard image build 
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'

jobs:
  wg-build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: wireguard 
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile
    - name: Push To Dockerhub
      id: push-to-docker
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io/adathor
        username: adathor
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

